# Momentum Scanner Playground
Tier 2 nightly scan: reads `data/watchlist.csv` → returns top momentum candidates.

In [1]:
# Cell 1 — Setup & import
import sys
sys.path.insert(0, 'backend/01_scanner')

from momentum_scanner import load_watchlist, calculate_momentum_score, run_scan
import pandas as pd

print('Imports OK')

Imports OK

In [2]:
# Cell 2 — Inspect raw watchlist
df = load_watchlist()
if df is None:
    raise FileNotFoundError(f'watchlist not found — run universe_filter.py first')
display(df.head(10))
print(f'\nColumns: {df.columns.tolist()}')

[scanner] loaded 65 stocks from data/watchlist.csv

,ticker,price,volume,atr,atr_pct,rsi,sma20,sma50,sector
0,NVDA,192.53,151446724,7.29,3.79,37.5,207.76,210.09,Electronic Technology
1,AMZN,232.69,77394835,7.94,3.41,39.5,244.03,256.13,Retail Trade
2,AAPL,283.78,77209808,8.16,2.87,41.2,298.29,291.50,Electronic Technology
3,T,22.72,61335176,0.58,2.57,41.8,23.07,24.52,Communications
4,NFLX,73.81,57967057,2.46,3.34,31.5,79.25,86.03,Technology Services
5,PFE,24.29,57453597,0.58,2.38,35.7,25.44,25.97,Health Technology
6,BAC,57.88,39048487,1.19,2.05,71.0,55.21,53.31,Finance
7,VZ,46.54,28996832,1.08,2.31,49.4,46.45,46.96,Communications
8,GOOG,334.69,28486391,11.41,3.41,33.4,358.71,366.63,Technology Services
9,CSCO,113.77,27192286,4.03,3.55,44.9,121.29,108.69,Electronic Technology

Columns: ['ticker', 'price', 'volume', 'atr', 'atr_pct', 'rsi', 'sma20', 'sma50', 'sector']

In [3]:
# Cell 3 — Run momentum scan and view top candidates
results = run_scan( min_score=3)
display(results)

[scanner] loaded 65 stocks from data/watchlist.csv
[scanner] 20 stocks with score >= 3
[scanner] returning top 15 candidates

   ticker   price  score   atr   rsi   sma20   sma50
0      KO   82.63      3  1.59  60.7   80.24   79.32
1     WFC   83.86      3  1.97  58.9   82.13   79.74
2     AXP  340.36      3  7.67  65.6  325.43  320.60
3     HWM  268.87      3  9.58  53.0  263.96  258.30
4     DHR  196.19      3  5.35  68.9  182.85  178.75
5     RTX  187.99      3  4.80  57.0  182.15  179.91
6      PM  180.77      3  4.86  52.9  178.48  175.87
7      HD  348.86      3  8.82  66.0  324.69  322.69
8     HON  232.21      3  7.05  58.0  224.66  221.37
9    FTNT  151.35      3  5.73  67.6  145.59  120.96
10    APH  163.72      3  6.41  62.8  154.43  144.60
11     MO   73.79      3  1.64  60.8   70.90   70.38
12      V  336.23      3  7.16  61.3  325.02  323.13
13   BKNG  181.46      3  6.63  62.4  169.38  169.12
14     PG  149.02      3  3.03  53.2  147.25  145.79

In [4]:
# Cell 4 — Parameter variation: score a pre-loaded DataFrame (no disk read)
# `df` from Cell 2 is scored directly; passing it skips load_watchlist().
results_from_df = run_scan(min_score=3, df=df)
display(results_from_df)

# Same result as the disk-loaded path in Cell 3.
if results_from_df is None or results is None:
    raise ValueError('run_scan returned None — watchlist failed to load')
print('matches Cell 3:', results_from_df.equals(results))

[scanner] 20 stocks with score >= 3
[scanner] returning top 15 candidates

   ticker   price  score   atr   rsi   sma20   sma50
0      KO   82.63      3  1.59  60.7   80.24   79.32
1     WFC   83.86      3  1.97  58.9   82.13   79.74
2     AXP  340.36      3  7.67  65.6  325.43  320.60
3     HWM  268.87      3  9.58  53.0  263.96  258.30
4     DHR  196.19      3  5.35  68.9  182.85  178.75
5     RTX  187.99      3  4.80  57.0  182.15  179.91
6      PM  180.77      3  4.86  52.9  178.48  175.87
7      HD  348.86      3  8.82  66.0  324.69  322.69
8     HON  232.21      3  7.05  58.0  224.66  221.37
9    FTNT  151.35      3  5.73  67.6  145.59  120.96
10    APH  163.72      3  6.41  62.8  154.43  144.60
11     MO   73.79      3  1.64  60.8   70.90   70.38
12      V  336.23      3  7.16  61.3  325.02  323.13
13   BKNG  181.46      3  6.63  62.4  169.38  169.12
14     PG  149.02      3  3.03  53.2  147.25  145.79

matches Cell 3: True

In [5]:
# Cell 5 — Parameter variation: cap the result size with top_n
top5 = run_scan(min_score=2, top_n=5)
display(top5)
print('rows returned:', 0 if top5 is None else len(top5))

[scanner] loaded 65 stocks from data/watchlist.csv
[scanner] 42 stocks with score >= 2
[scanner] returning top 5 candidates

  ticker   price  score   atr   rsi   sma20   sma50
0   BKNG  181.46      3  6.63  62.4  169.38  169.12
1     PG  149.02      3  3.03  53.2  147.25  145.79
2    HON  232.21      3  7.05  58.0  224.66  221.37
3    RTX  187.99      3  4.80  57.0  182.15  179.91
4   FTNT  151.35      3  5.73  67.6  145.59  120.96

rows returned: 5